### ISSUE TITLE
Use of deprecated API

### ISSUE THREAD

**Issue by depoll** [swingerman/ha-dual-smart-thermostat#312]
I'm now getting this warning on the latest version of Home Assistant:

> Entity None (<class 'custom_components.dual_smart_thermostat.climate.DualSmartThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature: 0>, please create a bug report at https://github.com/swingerman/ha-dual-smart-thermostat/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by swingerman** [comment]
Thanks for reporting this

**Comment by swingerman** [comment]
What version of the component are you using currently?

**Comment by swingerman** [comment]
We have already fixed this requirement. I assume you are on an older version, so I am closing this for now.

**Comment by depoll** [comment]
This is still happening for me on 0.9.8.3.  My most recent instance of this log entry is from yesterday morning and I'm using the latest release.

**Comment by swingerman** [comment]
Fiesd the issue and it will be included in the next release
