### ISSUE TITLE
v0.10.0 "Off" state doesn't work, keeps turning on AC

### ISSUE THREAD

**Issue by drulia** [swingerman/ha-dual-smart-thermostat#469]
Just updated to v0.10.0, here is my configuration for one of the climate entities:
```
  - platform: dual_smart_thermostat
    unique_id: c36d6ba68f474269
    name: Bedroom AC
    heater: input_boolean.bedroom_ac_heat_toggle
    cooler: input_boolean.bedroom_ac_cool_toggle
    # heat_cool_mode: true
    target_sensor: sensor.miegamojo_t_h_01_temperature_2
    min_temp: 17
    max_temp: 28
    cold_tolerance: 1.5
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 2
    keep_alive:
      minutes: 3
    precision: 0.1
    target_temp_step: 0.1
```

I don't normally use AC in winter, so the climate entities are set to Off state, but few moments after HA restarted after dual thermostat update I hear my ACs beep and see that they have turned on. Granted temperature set was 25C while actual temp is just 21.7, but it is in Off state. And climate entity still showing as being Off, but input_boolean is turned on: `turned on triggered by action Home Assistant Core Integration: Generic turn on`
If I change set temperature to the same as actual room temperature, then it stops turning the input_boolean ON. Basically it acts as if it is turned ON while state reports it as OFF.

**Comment by dpopovic** [comment]
Same or similar for me. I have heater or/and cooler switches as entry points for theromostat. Regardless of fact that climate entities are in off state they act as they are in on state and keep turning on devices.

**Comment by mat1990dj** [comment]
Same here, fuuuu*** the house was getting cold and did not figure out why. Watch out this is dangerous as it does not only waste enrgy but can damage systems.
For whatever reason the cooler switch gets turned on when the thermostat is in off state.
One of my configs:
`
  - platform: dual_smart_thermostat
    name: Bedroom
    unique_id: bedroom
    heater: input_boolean.heat_request_bedroom
    cooler: input_boolean.cool_request_bedroom
    target_sensor: sensor.office_temperature
    humidity_sensor: sensor.office_humidity
    heat_cool_mode: false
    #initial_hvac_mode: "off"
    min_temp: 60
    max_temp: 85
    precision: 0.1
    target_temp_step: 1
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 10
`

**Comment by swingerman** [comment]
## ✅ Fixed in v0.11.0-beta2

This critical issue has been fixed and is available in the beta release:

🔗 **[v0.11.0-beta2](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta2)**

### What was fixed:
- Devices will no longer turn on when thermostat is in OFF state
- Fixed during HA restart scenarios
- Fixed when temperature is changed in OFF mode
- Keep-alive feature continues to work correctly

### Root cause:
The `needs_control()` method was allowing the `force=True` parameter to bypass the OFF mode check, causing devices to activate unexpectedly during state restoration and temperature changes.

### Testing:
All 1209 tests passing ✅

Please test this beta release and report if you still experience any issues. Thank you for reporting this critical bug!

**Comment by aliaghil** [comment]
It is still the same: randomly turning the AC on/off.
This happened with the latest versions of HA (2025.12.3) and Dual Thermostat (0.11.0).
Any solution?

**Comment by swingerman** [comment]
Pleas echek [v0.11.1-beta3](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.1-beta3)
