### ISSUE TITLE
"aircondition only" configuration (UI) will not create an entity

### ISSUE THREAD

**Issue by filipjurik** [swingerman/ha-dual-smart-thermostat#484]
Hi,

as I wrote earlier, this problem persists even in the latest 7th beta version.
HA OS 2025.12.2

https://github.com/user-attachments/assets/947524ab-a4dd-45b8-a1f8-2b0ffdd27126

**Comment by swingerman** [comment]
I see the issues. Ia lso did some quick test and I see the entity is created. Can you please confirm that besides the issue witht e configuration flow the actual entity is created?

**Comment by swingerman** [comment]
Fixed in v0.11.0-beta9: https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta9

**Comment by filipjurik** [comment]
I completely uninstalled the previous version and reinstalled beta 9.
restarted ha after uninstalling, restarted after installing

in core_entity_registry the entity is created, but in HA it is still unavailable.


**entry in core_entity_registry:** 

      {"aliases":[],"area_id":null,"categories":{},"capabilities":{"hvac_modes":["cool","off"],"min_temp":7.0,"max_temp":35.0,"target_temp_step":1.0},"config_entry_id":"01KC95X2JD5BMNJCRJZYGZTG4C","config_subentry_id":null,"created_at":"2025-12-12T11:42:24.337743+00:00","device_class":null,"device_id":null,"disabled_by":null,"entity_category":null,"entity_id":"climate.cccc","hidden_by":null,"icon":null,"id":"526b3bff7c00ba600fb66aed7ad1ebae","has_entity_name":false,"labels":[],"modified_at":"2025-12-12T11:42:41.512585+00:00","name":null,"options":{"conversation":{"should_expose":false}},"original_device_class":null,"original_icon":null,"original_name":"cccc","platform":"dual_smart_thermostat","suggested_object_id":null,"supported_features":384,"translation_key":null,"unique_id":"01KC95X2JD5BMNJCRJZYGZTG4C","previous_unique_id":null,"unit_of_measurement":null}


still the same problem

<img width="443" height="451" alt="Image" src="https://github.com/user-attachments/assets/fa2447a6-3148-4be2-bc36-83be3f964d77" />


**error in log:**

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:676
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 12:35:10 (7 occurrences)
Last logged: 12:45:35

Error adding entity climate.airc for domain climate with platform dual_smart_thermostat
Error adding entity climate.cccc for domain climate with platform dual_smart_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 752, in async_added_to_hass
    async_track_time_interval(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.hass,
        ^^^^^^^^^^
        self._async_control_climate,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._keep_alive,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1691, in async_track_time_interval
    seconds = interval.total_seconds()
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'total_seconds'

**Comment by swingerman** [comment]
Thank you for the additional logs and config! I've identified and fixed the root cause.

## Root Cause

The config flow stores  (and other time values like , ) as **numeric values in seconds** (int/float) because they use NumberSelector:

```python
# From config flow - stored as float
{"keep_alive": 300.0}  # 300 seconds
```

However,  expects these to be **timedelta objects**:

```python
# Line 752 in climate.py
async_track_time_interval(
    self.hass,
    self._async_control_climate,
    self._keep_alive,  # Expected: timedelta, Got: float
)
```

When Home Assistant's `async_track_time_interval` receives a float instead of timedelta, it tries to call `.total_seconds()` on it, causing:

```
AttributeError: 'float' object has no attribute 'total_seconds'
```

## Fix

I've updated `_normalize_config_numeric_values()` in `climate.py` to convert time-based config values from seconds (int/float) to timedelta objects:

```python
# Time-based keys that need conversion from seconds to timedelta
time_keys = [CONF_KEEP_ALIVE, CONF_MIN_DUR, CONF_STALE_DURATION]

for key in time_keys:
    if key in config and config[key] is not None:
        value = config[key]
        if not isinstance(value, timedelta):
            if isinstance(value, (int, float)):
                config[key] = timedelta(seconds=value)
```

This fix:
- ✅ Converts float/int seconds to timedelta during entity setup
- ✅ Preserves existing timedelta values (for YAML configs)
- ✅ Applies to all time-based settings (keep_alive, min_cycle_duration, stale_duration)
- ✅ All 1245 tests pass including 5 new tests specifically for this fix

The fix is included in the same PR #486 that fixed the precision/temp_step issue. I'll create a new beta release with both fixes.

**Comment by swingerman** [comment]
Fixed in v0.11.0-beta10: https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta10

**Comment by filipjurik** [comment]
sorry, :)
new log and the same problem is still there


Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:676
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 13:39:03 (1 occurrence)
Last logged: 13:39:03

Error adding entity climate.aaa for domain climate with platform dual_smart_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 772, in async_added_to_hass
    async_track_time_interval(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.hass,
        ^^^^^^^^^^
        self._async_control_climate,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._keep_alive,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1691, in async_track_time_interval
    seconds = interval.total_seconds()
              ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'total_seconds'

**Comment by swingerman** [comment]
Fixed in v0.11.0-beta11 - handles dict-to-timedelta conversion after HA storage deserialization. https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta11

**Comment by filipjurik** [comment]
ok, still the same error.

but I'll describe what I found out.

when I create a new configuration, it creates an entity and it is also accessible.


<img width="483" height="632" alt="Image" src="https://github.com/user-attachments/assets/d8bc39cc-bffe-44b8-89c9-21896a3e0063" />

<img width="479" height="426" alt="Image" src="https://github.com/user-attachments/assets/77212a15-e96c-4471-a804-ca0c2fb74d7d" />

<img width="328" height="466" alt="Image" src="https://github.com/user-attachments/assets/f54d4136-0cde-490d-9db6-ac682c927f00" />

<img width="482" height="322" alt="Image" src="https://github.com/user-attachments/assets/df3ae50b-75a5-4332-b1f6-4f4dc6aabe14" />

<img width="466" height="475" alt="Image" src="https://github.com/user-attachments/assets/11a77169-6cf2-4401-b054-67ea7158ae93" />


but if I want to reconfigure "target temp"
it gives a "keep alive" error and won't let me leave the value at 0h00m00s.
I have to change it to at least 1s

<img width="483" height="630" alt="Image" src="https://github.com/user-attachments/assets/4ff89326-c53a-44cb-8834-193ef0e3036a" />

<img width="477" height="631" alt="Image" src="https://github.com/user-attachments/assets/330df079-4ed5-400d-824c-0e0604ef6263" />




<img width="479" height="202" alt="Image" src="https://github.com/user-attachments/assets/d436176d-6fb1-4d49-887d-f25b676db970" />

<img width="482" height="257" alt="Image" src="https://github.com/user-attachments/assets/45905fb7-ac1a-4680-a7fa-ac87be91ba74" />

Then the configuration of the "Temperature Presets" will take place as I entered them at the beginning.


**BUT, now the entity is no longer accessible.**

<img width="463" height="479" alt="Image" src="https://github.com/user-attachments/assets/2a4b71d5-6186-459c-b4a8-7b7a817ba417" />


Only after the second configuration (reconfiguration) does the error I already sent appear in the log.

**Comment by filipjurik** [comment]
and also the difference between created entities in core.entity_registry

**after entity creation / first configuration**
      {"aliases":[],"area_id":null,"categories":{},"capabilities":{"hvac_modes":["cool","off"],"min_temp":7,"max_temp":35,"target_temp_step":0.1,"preset_modes":["away","home","none"]},"config_entry_id":"01KC9KDS4Y7J1Z0CE3B492B00Q","config_subentry_id":null,"created_at":"2025-12-12T15:38:43.232862+00:00","device_class":null,"device_id":null,"disabled_by":null,"entity_category":null,"entity_id":"climate.zzz","hidden_by":null,"icon":null,"id":"0f2b7115370ff4b8477cadba4092ffd9","has_entity_name":false,"labels":[],"modified_at":"2025-12-12T15:38:43.237694+00:00","name":null,"options":{"conversation":{"should_expose":false}},"original_device_class":null,"original_icon":null,"original_name":"zzz","platform":"dual_smart_thermostat","suggested_object_id":null,"supported_features":401,"translation_key":null,"unique_id":"01KC9KDS4Y7J1Z0CE3B492B00Q","previous_unique_id":null,"unit_of_measurement":null}


**after reconfiguration**
      {"aliases":[],"area_id":null,"categories":{},"capabilities":{"hvac_modes":["cool","off"],"min_temp":7.0,"max_temp":35.0,"target_temp_step":1.0},"config_entry_id":"01KC9KDS4Y7J1Z0CE3B492B00Q","config_subentry_id":null,"created_at":"2025-12-12T15:38:43.232862+00:00","device_class":null,"device_id":null,"disabled_by":null,"entity_category":null,"entity_id":"climate.zzz","hidden_by":null,"icon":null,"id":"0f2b7115370ff4b8477cadba4092ffd9","has_entity_name":false,"labels":[],"modified_at":"2025-12-12T15:39:54.196853+00:00","name":null,"options":{"conversation":{"should_expose":false}},"original_device_class":null,"original_icon":null,"original_name":"zzz","platform":"dual_smart_thermostat","suggested_object_id":null,"supported_features":384,"translation_key":null,"unique_id":"01KC9KDS4Y7J1Z0CE3B492B00Q","previous_unique_id":null,"unit_of_measurement":null}


**after reconfiguration, min_temp and max_temp change from integers to decimals, "target_temp_step" does not remember the original value, and the "preset_modes" configuration is completely lost**

**Comment by swingerman** [comment]
This is very helpful

**Comment by swingerman** [comment]
**Update on PR #490**: Added fix for dict-to-timedelta normalization in config/options flows. This should resolve:

- Options flow displaying keep_alive as 0h00m00s 
- Being forced to re-enter keep_alive value
- Entity becoming unavailable after options flow

The fix ensures that when Home Assistant deserializes timedelta values as dicts from storage, both config_flow and options_flow normalize them back to timedelta before building forms or using the values.

**Please test with beta12** (once released) and let us know if:
1. Options flow displays keep_alive correctly (not 0h00m00s)
2. target_temp_step stays at 0.1 (doesn't revert to 1.0)
3. Presets are preserved after going through options flow
4. No AttributeError after saving options

PR #490: https://github.com/swingerman/ha-dual-smart-thermostat/pull/490

**Comment by swingerman** [comment]
Beta12 is now available with a complete fix for the dict-to-timedelta issue: https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v6.2.0-beta12

This version adds proper storage deserialization in both config and options flows. Please test and confirm if this resolves the issue completely.

**Comment by filipjurik** [comment]
sorry friend, but still the same error.
after the first configuration the entity is created and is functional,
after configuration,


<img width="790" height="67" alt="Image" src="https://github.com/user-attachments/assets/2355fbdc-b5e2-4867-bba6-c69f2497c48b" />

target_temperature changes, keep_alive still cannot be 0, it does not remember the home and away presets checkbox (in my case) and finally it stops being accessible.

in the log the same error, and in core.entity_registry
the preset_modes setting disappears from the entity

it behaves exactly as I described

**Comment by filipjurik** [comment]
<img width="1274" height="289" alt="Image" src="https://github.com/user-attachments/assets/e8d489ea-429e-464e-938d-a0a881782f08" />

**Comment by swingerman** [comment]
I also saw the preset issues. Fixing them right now. That keep alive issue gives me hard time though

**Comment by filipjurik** [comment]
Unfortunately I'm not a programmer and I don't understand it, I'm just trying and trying to think logically and compare.
I wish you strong nerves and success.
Otherwise, great work.

If it helps, I'll be happy to test further and help as much as I can.

**Comment by swingerman** [comment]
Please check [v0.11.0-beta12](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta12). I fixed most of the issues.

**Comment by filipjurik** [comment]
hi, so great, "air condition only" works. great. Just one thing... after the first configuration I set a "preset" like Home, Away... and everything works as it should. After reconfiguration I decide that I want to remove " Away" for example but it doesn't work. It stays there.

**Comment by filipjurik** [comment]
and when I remove all the "preset temperature" checkboxes and submit, they can't be added at all during the next configuration. but they are still there as originally configured.

**Comment by filipjurik** [comment]
theoretical question: 
1. is it possible to not display the "none" preset?
2.  is it possible to set "hot tolerance" and "cold tolerance" to 0?

**Comment by swingerman** [comment]
Theoretically, it's possible not to display the "none" preset, but I would only go for it optionally (advanced setting). You can open a feature request for that.

**Comment by swingerman** [comment]
If you deselect all presets in the options flow (configure) you still can run the reconfigure flow. There are two different flows in HA. The options flow runs when you click on the "Configure" button, and the reconfigure flow runs from the extra options menu.

**Comment by filipjurik** [comment]
yes, but!
there was an error somewhere...
i tried "reconfigure" from the menu.

<img width="476" height="512" alt="Image" src="https://github.com/user-attachments/assets/9a93f23e-bb0e-4033-a628-b7908be84dc7" />

**Comment by filipjurik** [comment]
sorry, here is the LOG:


Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:481
First occurred: 23:06:04 (1 occurrence)
Last logged: 23:06:04

Error handling request from 78.99.176.28
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 87, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 234, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 121, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 346, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 393, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 493, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/config_flow.py", line 218, in async_step_reconfigure_confirm
    return await self._async_step_system_config()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/config_flow.py", line 241, in _async_step_system_config
    return await self.async_step_basic_ac_only()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/config_flow.py", line 320, in async_step_basic_ac_only
    schema = get_basic_ac_schema(defaults=self.collected_config, include_name=True)
  File "/config/custom_components/dual_smart_thermostat/schemas.py", line 329, in get_basic_ac_schema
    timing_fields = get_timing_fields_for_section(
        defaults=defaults, include_keep_alive=True
    )
  File "/config/custom_components/dual_smart_thermostat/schemas.py", line 278, in get_timing_fields_for_section
    min_dur_default = seconds_to_duration(min_dur_value)
  File "/config/custom_components/dual_smart_thermostat/schema_utils.py", line 22, in seconds_to_duration
    hours = seconds // 3600
            ~~~~~~~~^^~~~~~
TypeError: unsupported operand type(s) for //: 'dict' and 'int'

**Comment by swingerman** [comment]
Please check [v0.11.0-beta13](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta13). It fixes more pre-release issues and improves the reconfigure flow as well.

**Comment by filipjurik** [comment]
great job, works perfectly.
thank you very much.

**Comment by filipjurik** [comment]
Sorry, there was a small error in reconfiguring  from the menu.

<img width="476" height="629" alt="Image" src="https://github.com/user-attachments/assets/ee60d53d-cc67-418c-94a6-5fe00ba2b69b" />

**Comment by swingerman** [comment]
Please try [v0.11.0-beta14](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.0-beta14)

**Comment by filipjurik** [comment]
I tried it and haven't found any errors yet. Good job.
