### ISSUE TITLE
[bug] Problem with multiple thermostats

### ISSUE THREAD

**Issue by michaelltaylor** [swingerman/ha-dual-smart-thermostat#499]
I have set up multiple thermostats (5) in order to control motorized heat vents, space heaters, and window air conditioners in different rooms. Since the last update, whenever I restart Home Assistant, several of my thermostats are unavailable. To restore them, I have to open the config file, make some trivial change like adding a space at the end, then save the file and do a quick restart of the Home Assistant YAML config. I then have to correct all the setpoints on the thermostats. I have no idea what's causing this or if there's a way to fix it on my end, but it seems only the thermostats that control both heating and cooling are affected. It's becoming unusable.

**Comment by swingerman** [comment]
Could you please prvide your config of the failing thermostats. As well as error logs you might have.

**Comment by michaelltaylor** [comment]
Here's my YAML code for  the thermostats. It's in a file called thermostats.yaml and is referenced from configuration.yaml with "climate: !include thermostats.yaml" 
I don't have any error logs.

```
  - platform: dual_smart_thermostat
    name: Game Room Thermostat
    unique_id: climate.game_room_thermostat
    heater: input_boolean.game_room_vents
    secondary_heater: switch.game_room_heater
    secondary_heater_timeout: "00:10:00"
    secondary_heater_dual_mode: false
    openings:
      - entity_id: binary_sensor.game_room_window
        timeout: "00:00:15"
        closing_timeout: "00:00:15"
      - entity_id: binary_sensor.game_room_door
        timeout: "00:00:15"
        closing_timeout: "00:00:15"
    ac_mode: false
    target_sensor: sensor.game_room_sensor_temperature_local
    initial_hvac_mode: "off"
    keep_alive:
      minutes: 5
    hot_tolerance: 0.3
    cold_tolerance: 0
    min_temp: 62
    max_temp: 80
    precision: 0.1
    target_temp_step: 1
       
  - platform: dual_smart_thermostat
    name: Master Bedroom Thermostat
    unique_id: climate.master_bedroom_thermostat
    heater: binary_sensor.master_bedroom_vent
    secondary_heater: switch.master_bedroom_heater_local
    secondary_heater_timeout: "00:10:00"
    secondary_heater_dual_mode: false
    cooler: switch.master_bedroom_air_conditioner
    target_sensor: sensor.sensi_master_bedroom_thermostat_temperature
    initial_hvac_mode: "heat_cool"
    heat_cool_mode: true
    min_cycle_duration:
      minutes: 3
    keep_alive:
      minutes: 5
    hot_tolerance: 1
    cold_tolerance: 1
    min_temp: 62
    max_temp: 80
    precision: 0.1
    target_temp_step: 1

  - platform: dual_smart_thermostat
    name: Computer Room Thermostat
    unique_id: climate.computer_room_thermostat
    heater: input_boolean.computer_room_heater
    secondary_heater: switch.computer_room_heater
    secondary_heater_timeout: "00:10:00"
    secondary_heater_dual_mode: false
    cooler: input_boolean.computer_room_cooler
    target_sensor: sensor.computer_room_temperature_sensor_temperature
    initial_hvac_mode: "heat_cool"
    heat_cool_mode: true
    min_cycle_duration:
      minutes: 3
    keep_alive:
      minutes: 5
    openings:
      - entity_id: input_boolean.microwave_power_lockout
        timeout: 00:00:05 # delay before pausing HVAC 
        closing_timeout: 00:03:00 # delay before resuming 
    openings_scope: [cool]
    hot_tolerance: 0.3
    cold_tolerance: 0.3
    min_temp: 62
    max_temp: 80
    precision: 0.1
    target_temp_step: 1

  - platform: dual_smart_thermostat
    name: Nico's Room Thermostat
    unique_id: climate.nico_s_room_thermostat
    heater: switch.nico_s_heater
    target_sensor: sensor.nico_s_room_thermometer_temperature
    initial_hvac_mode: "heat"
    hot_tolerance: 0.3
    cold_tolerance: 0.3
    min_temp: 62
    max_temp: 80
    precision: 0.1
    target_temp_step: 1
    
  - platform: dual_smart_thermostat
    name: First Floor Thermostat
    unique_id: climate.first_floor_thermostat
    heater: input_boolean.living_room_heat
    cooler: switch.air_conditioner
    target_sensor: sensor.living_room_thermostat_temperature
    openings:
      - entity_id: binary_sensor.dining_room_window
        timeout: "00:00:15"
        closing_timeout: "00:00:15"
      - entity_id: binary_sensor.kitchen_window
        timeout: "00:00:15"
        closing_timeout: "00:00:15"
      - entity_id: binary_sensor.living_room_window_side
        timeout: "00:00:15"
        closing_timeout: "00:00:15" 
      - entity_id: binary_sensor.living_room_window_front
        timeout: "00:00:15"
        closing_timeout: "00:00:15" 
    initial_hvac_mode: "heat_cool"
    heat_cool_mode: true
    min_cycle_duration:
      minutes: 3
    keep_alive:
      minutes: 3
    hot_tolerance: 1
    cold_tolerance: 1.3
    min_temp: 62
    max_temp: 80
    precision: 0.1
    target_temp_step: 1
```

**Comment by michaelltaylor** [comment]
Since only the thermostats that control cooling are affected, could this be a load order issue where the thermostats are loading before the cooling entities are available?

**Comment by swingerman** [comment]
- Could you please confrim which version are you using?
- Could you try to catch some error logs whn thsi happens?

**Comment by michaelltaylor** [comment]
The issue was happening with V0.11.0
I only update to stable versions, not beta versions.
I am currently downgraded to v0.9.12 for the time being and noticed that also cleared up a lag issue I was experiencing with Home Assistant as a whole.
I don't know how to capture logs for the issue since it only happens at boot up time, and not every time. If you can suggest steps to do so, I will try.

My Home Assistant environment is as follow...
Installation method: Home Assistant OS
Core: 2025.12.3
Supervisor: 2025.12.3
Operating System: 16.3
Frontend: 20251203.2

Installed bare metal (no containers)

**Comment by swingerman** [comment]
The quickest way to get some logs is restarting HA to reprodcue the error and then go to settings -> system -> logs. HA should log the issue with the thermostat it could not initialize

**Comment by swingerman** [comment]
please check [v0.11.1-beta1](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.1-beta1). This can potentially fix it

**Comment by michaelltaylor** [comment]
This is not fixed, so seeing this got closed was disappointing. Hopefully this will still get seen...

I upgraded to v0.11.1-beta1 and rebooted. One of my thermostats showed Unavailable. I rebooted again, and  a different thermostat showed unavailable. I pulled the logs as you described. This is what I got...


Logger: custom_components.dual_smart_thermostat.climate.climate.game_room_thermostat
Source: custom_components/dual_smart_thermostat/climate.py:413
integration: dual_smart_thermostat (documentation, issues)
First occurred: 07:21:05 (1 occurrence)
Last logged: 07:21:05

The configuration option 'min_cycle_duration' will be ignored because incompatible with the defined option 'keep_alive'.



Logger: custom_components.dual_smart_thermostat.climate.climate.master_bedroom_thermostat
Source: custom_components/dual_smart_thermostat/climate.py:413
integration: dual_smart_thermostat (documentation, issues)
First occurred: 07:21:05 (1 occurrence)
Last logged: 07:21:05

The configuration option 'min_cycle_duration' will be ignored because incompatible with the defined option 'keep_alive'.



Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:676
integration: Climate (documentation, issues)
First occurred: 07:21:05 (1 occurrence)
Last logged: 07:21:05

Error adding entity climate.computer_room_thermostat for domain climate with platform dual_smart_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 898, in async_added_to_hass
    await self.async_set_hvac_mode(hvac_mode, is_restore=True)
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 1168, in async_set_hvac_mode
    await self.hvac_device.async_set_hvac_mode(hvac_mode)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 139, in async_set_hvac_mode
    await super().async_set_hvac_mode(hvac_mode)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/multi_hvac_device.py", line 123, in async_set_hvac_mode
    await self.async_control_hvac(force=True)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 72, in async_control_hvac
    await self._async_control_heat_cool(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 159, in _async_control_heat_cool
    await self.async_heater_cooler_toggle(time, force)
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 164, in async_heater_cooler_toggle
    too_cold, too_hot, tolerance_device = self.is_cold_or_hot()
                                          ~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py", line 98, in is_cold_or_hot
    self.environment.cur_temp >= self.environment.target_temp_low
TypeError: '>=' not supported between instances of 'NoneType' and 'float'



Logger: custom_components.dual_smart_thermostat.climate.climate.nico_s_room_thermostat
Source: custom_components/dual_smart_thermostat/climate.py:413
integration: dual_smart_thermostat (documentation, issues)
First occurred: 07:21:05 (1 occurrence)
Last logged: 07:21:05

The configuration option 'min_cycle_duration' will be ignored because incompatible with the defined option 'keep_alive'.

**Comment by swingerman** [comment]
## Additional Fix in v0.11.1-beta2

Thank you for providing the error logs! They revealed a **second issue** that was causing the crashes.

### The Second Issue

Your error logs showed:
```python
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

This occurred at:
```python
self.environment.cur_temp >= self.environment.target_temp_low
```

### Root Cause Analysis

The issue was introduced in **v0.11.0** by the fix for issue #10 (tolerance behavior improvements). Here's what happened:

**In v0.9.12 (working):**
- Code used helper methods `is_too_cold()` and `is_too_hot()` 
- These methods had built-in None checks
- ✅ No crashes during startup

**In v0.11.0 (broken):**
- Fix for #10 added direct temperature comparisons: `cur_temp >= target_temp_low`
- These new comparisons didn't include None checks
- ❌ Crashed when temperature sensor hadn't provided a value yet during startup

### The Fix

Added None checks in `heater_cooler_device.py` before temperature comparisons:

```python
# Guard against None values during startup (issue #499)
if (
    self.environment.cur_temp is None
    or self.environment.target_temp_low is None
):
    target_reached = False
else:
    target_reached = (
        self.environment.cur_temp >= self.environment.target_temp_low
    )
```

This follows the same pattern already used in `heater_device.py` and `cooler_device.py`.

### Complete Solution

**v0.11.1-beta1** fixed: Service calls on UNAVAILABLE entities  
**v0.11.1-beta2** fixed: None temperature value comparisons

Together, these releases fully resolve the startup issues you reported.

### Testing

Could you please test **v0.11.1-beta2** and let us know if this resolves the issue? You can install it from the [releases page](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.11.1-beta2).

### Changes
- File: `custom_components/dual_smart_thermostat/hvac_device/heater_cooler_device.py`
- Lines: 98-106 (heater active case), 121-129 (cooler active case)
- Test: Added `test_yaml_heater_cooler_none_temperature_on_startup`
- All 1260 tests pass ✅

**Comment by michaelltaylor** [comment]
I'm in a meeting right now, but I will test it within the hour.

**Comment by michaelltaylor** [comment]
I upgraded to v0.11.1-beta2 and rebooted. The thermostats appear to have loaded, but I still got errors in the log...


Logger: custom_components.dual_smart_thermostat.climate.climate.nico_s_room_thermostat
Source: custom_components/dual_smart_thermostat/climate.py:413
integration: Dual Smart Thermostat (documentation, issues)
First occurred: 12:28:19 (1 occurrence)
Last logged: 12:28:19

The configuration option 'min_cycle_duration' will be ignored because incompatible with the defined option 'keep_alive'.



Logger: custom_components.dual_smart_thermostat.climate.climate.master_bedroom_thermostat
Source: custom_components/dual_smart_thermostat/climate.py:413
integration: Dual Smart Thermostat (documentation, issues)
First occurred: 12:28:19 (1 occurrence)
Last logged: 12:28:19

The configuration option 'min_cycle_duration' will be ignored because incompatible with the defined option 'keep_alive'.



Logger: custom_components.dual_smart_thermostat.climate.climate.game_room_thermostat
Source: custom_components/dual_smart_thermostat/climate.py:413
integration: Dual Smart Thermostat (documentation, issues)
First occurred: 12:28:19 (1 occurrence)
Last logged: 12:28:19

The configuration option 'min_cycle_duration' will be ignored because incompatible with the defined option 'keep_alive'.



Logger: homeassistant.helpers.event
Source: helpers/template/__init__.py:463
First occurred: 12:28:07 (1 occurrence)
Last logged: 12:28:07

Error while processing template: Template<template=(.secondary { visibility: hidden; } .secondary:before { visibility: visible; content: "Temp: {{ states('sensor.kitchen_thermometer_temperature') | float | round(1) }}°F"; }) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 1551, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 461, in async_render
    render_result = render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template/context.py", line 45, in render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 6, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 1554, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template/helpers.py", line 24, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '.secondary {
  visibility: hidden; 
}
.secondary:before {
  visibility: visible;
  content: "Temp: {{ states('sensor.kitchen_thermometer_temperature') | float | round(1) }}°F";
}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 579, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template/__init__.py", line 463, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '.secondary {
  visibility: hidden; 
}
.secondary:before {
  visibility: visible;
  content: "Temp: {{ states('sensor.kitchen_thermometer_temperature') | float | round(1) }}°F";
}' but no default was specified

**Comment by swingerman** [comment]
## ✅ Fix Confirmed Working!

Great news! The thermostats loaded successfully with v0.11.1-beta2. The TypeError crash is now fixed.

### About the Warnings

The warnings you're seeing are **expected and not errors**:

#### 1. "min_cycle_duration will be ignored because incompatible with keep_alive"

This is **informational** - not an error. Looking at your configuration:

```yaml
Master Bedroom, Computer Room, First Floor:
  min_cycle_duration:
    minutes: 3
  keep_alive:
    minutes: 5  # or 3
```

You have both `min_cycle_duration` and `keep_alive` configured, but they're **incompatible** because:
- `min_cycle_duration` prevents the device from cycling too frequently
- `keep_alive` sends periodic commands to keep the device responsive

When both are present, `keep_alive` takes priority and `min_cycle_duration` is ignored.

**Recommendation:** Remove `min_cycle_duration` from thermostats that use `keep_alive`:

```yaml
# Good - Use one or the other
climate:
  - platform: dual_smart_thermostat
    name: Master Bedroom Thermostat
    # min_cycle_duration: minutes: 3  # Remove this line
    keep_alive:
      minutes: 5
```

#### 2. Template Error for kitchen_thermometer_temperature

This error is **not related to dual_smart_thermostat**. It's a template rendering issue in your HA configuration where a sensor has 'unknown' state. This is in your custom YAML/template code, not our component.

### Summary

🎉 **Issue #499 is RESOLVED** - Thermostats now load successfully during HA restart!

The warnings are just informational about configuration cleanup you can do when convenient. The component is working correctly.

Thanks for testing and providing such detailed logs! Please let us know if you encounter any other issues.

**Comment by michaelltaylor** [comment]
It's much better than it was, but I still see one of the thermostats fail to load occasionally. It's much easier to deal with now that it isn't every time. I can live with it, but the issue isn't totally resolved.
